<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="..\..\ClientInterfaces\CLI\CLI.cs" Link="CLI.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Syroot.Windows.IO.KnownFolders" Version="1.3.0" />
	<TrimmerRootAssembly Include="NAudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
